all: cuda

cuda80:
	docker pull nvidia/cuda:8.0-cudnn6-devel-ubuntu16.04

cuda90:
	docker pull nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04

cuda91:
	docker pull nvidia/cuda:9.1-cudnn7-devel-ubuntu16.04

cuda92:
	docker pull nvidia/cuda:9.2-cudnn7-devel-ubuntu16.04

cuda: cuda80 cuda90
